aj:
  captcha:
    # 验证码类型 1.滑动拼图 blockPuzzle  2.文字点选 clickWord
    type: BLOCKPUZZLE
    # 缓存local/redis...
    cache-type: local
    # 滑动验证，底图路径，不配置将使用默认图片
    ##支持全路径
    # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
    jigsaw: classpath:images/jigsaw
    # 右下角水印文字(我的水印)
    water-mark: 江苏博宇鑫信息科技股份有限公司
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 2
    history-data-clear-enable: true
    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: true
    # 验证失败5次，get接口锁定
    req-get-lock-limit: 5
    # 验证失败后，锁定时间间隔,s
    req-get-lock-seconds: 360
    # get接口一分钟内请求数限制
    req-get-minute-limit: 30
    # check接口一分钟内请求数限制
    req-check-minute-limit: 30
    # verify接口一分钟内请求数限制
    req-verify-minute-limit: 30
