spring:
  cloud:
    gateway:
      enabled: true
      routes:  # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: frontend # 路由唯一标识
          uri: http://localhost:9527
          predicates:
            - Path=/,/static/**,/favicon.ico,/index.html

        - id: user
          uri: lb://user # 需要转发的地址  lb: 使用nacos中的本地负载均衡策 // 服务名
          predicates:
            - Path=/user/**

        - id: files
          uri: lb://files
          predicates:
            - Path=/files/**

logging:
  level:
    root: info

